# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: Install poetry
          command: pip install poetry
      - run:
          name: Install dependencies
          command: poetry install
      - run: poetry run python app/hello.py

  test:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
